System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "dist/flatworld.js": [
      "bundles/fullModuleBundle.js",
      "bundles/coreBundle.js",
      "components/map/extensions/basicActions/basicActions.js",
      "components/map/UIs/default/utils/arrows.js",
      "components/map/UIs/default/layout/index.js",
      "factories/index.js",
      "components/map/extensions/hexagons/index.js",
      "components/logger/log.js",
      "components/map/extensions/mapMovement/mapMovement.js",
      "components/map/UIs/default/default.js",
      "components/preloading/preloading.js",
      "components/utilities/polyfills.js",
      "bundles/strippedCoreBundle.js",
      "components/map/UIs/default/layout/CSSRules.js",
      "components/map/extensions/hexagons/utils/hexagonMath.js",
      "components/utilities/general.js",
      "npm:babel-runtime@5.8.24/helpers/class-call-check.js",
      "components/map/core/baseEventlisteners/baseEventlisteners.js",
      "components/map/core/move/mapDrag.js",
      "components/map/UIs/default/layout/templates.js",
      "factories/horizontalHexaFactory.js",
      "components/map/extensions/hexagons/eventListeners/select.js",
      "components/map/core/zoom/mapZoom.js",
      "components/map/extensions/hexagons/utils/createHexagon.js",
      "components/map/extensions/hexagons/selectHexagonPlugin.js",
      "components/map/extensions/hexagons/Objects.js",
      "npm:loglevel@1.4.0.js",
      "npm:babel-runtime@5.8.24/core-js/object/assign.js",
      "npm:babel-runtime@5.8.24/helpers/get.js",
      "npm:babel-runtime@5.8.24/helpers/inherits.js",
      "npm:babel-runtime@5.8.24/helpers/create-class.js",
      "npm:q@1.4.1.js",
      "assets/lib/jquery/jquery-css-ajax-effects.min.js",
      "assets/lib/polyfills/es6StringPoly/es6StringPoly.js",
      "assets/lib/hamsterjs/hamster.js",
      "components/map/core/Objects.js",
      "components/map/core/mapEvents.js",
      "components/map/core/UI.js",
      "npm:loglevel@1.4.0/lib/loglevel.js",
      "components/map/core/utils/index.js",
      "github:components/handlebars.js@4.0.5.js",
      "components/map/core/eventlisteners.js",
      "components/map/core/MapDataManipulator.js",
      "components/map/core/Map.js",
      "components/map/core/ObjectManager.js",
      "components/map/core/MapLayers.js",
      "components/map/core/UI_themeBase.js",
      "npm:core-js@1.1.4/library/fn/object/assign.js",
      "npm:babel-runtime@5.8.24/core-js/object/get-own-property-descriptor.js",
      "npm:babel-runtime@5.8.24/core-js/object/create.js",
      "npm:babel-runtime@5.8.24/core-js/object/set-prototype-of.js",
      "npm:babel-runtime@5.8.24/core-js/object/define-property.js",
      "github:hammerjs/hammer.js@2.0.6.js",
      "npm:q@1.4.1/q.js",
      "assets/lib/pixi/pixi.js",
      "components/map/core/utils/effects.js",
      "components/map/core/utils/utils.js",
      "components/map/core/utils/dataManipulation.js",
      "npm:babel-runtime@5.8.24/core-js/set.js",
      "npm:core-js@1.1.4/library/modules/$.core.js",
      "github:components/handlebars.js@4.0.5/handlebars.js",
      "npm:core-js@1.1.4/library/modules/es6.object.assign.js",
      "npm:core-js@1.1.4/library/fn/object/create.js",
      "npm:babel-runtime@5.8.24/core-js/promise.js",
      "npm:core-js@1.1.4/library/fn/object/set-prototype-of.js",
      "npm:core-js@1.1.4/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.1.4/library/fn/object/define-property.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:hammerjs/hammer.js@2.0.6/hammer.js",
      "npm:babel-runtime@5.8.24/core-js/object/keys.js",
      "npm:core-js@1.1.4/library/fn/set.js",
      "npm:core-js@1.1.4/library/modules/$.js",
      "npm:core-js@1.1.4/library/modules/$.def.js",
      "npm:core-js@1.1.4/library/fn/promise.js",
      "npm:core-js@1.1.4/library/modules/$.assign.js",
      "npm:core-js@1.1.4/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.1.4/library/modules/es6.object.get-own-property-descriptor.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:core-js@1.1.4/library/modules/es6.object.to-string.js",
      "npm:core-js@1.1.4/library/fn/object/keys.js",
      "npm:core-js@1.1.4/library/modules/es6.string.iterator.js",
      "npm:core-js@1.1.4/library/modules/es6.set.js",
      "npm:core-js@1.1.4/library/modules/web.dom.iterable.js",
      "npm:core-js@1.1.4/library/modules/$.global.js",
      "npm:core-js@1.1.4/library/modules/$.fails.js",
      "npm:core-js@1.1.4/library/modules/es7.set.to-json.js",
      "npm:core-js@1.1.4/library/modules/$.to-object.js",
      "npm:core-js@1.1.4/library/modules/$.iobject.js",
      "npm:core-js@1.1.4/library/modules/$.enum-keys.js",
      "npm:core-js@1.1.4/library/modules/$.to-iobject.js",
      "npm:core-js@1.1.4/library/modules/$.set-proto.js",
      "npm:core-js@1.1.4/library/modules/$.object-sap.js",
      "npm:core-js@1.1.4/library/modules/es6.promise.js",
      "npm:process@0.11.2.js",
      "npm:core-js@1.1.4/library/modules/$.iterators.js",
      "npm:core-js@1.1.4/library/modules/es6.object.keys.js",
      "npm:core-js@1.1.4/library/modules/$.iter-define.js",
      "npm:core-js@1.1.4/library/modules/$.string-at.js",
      "npm:core-js@1.1.4/library/modules/$.collection-strong.js",
      "npm:core-js@1.1.4/library/modules/es6.array.iterator.js",
      "npm:core-js@1.1.4/library/modules/$.collection.js",
      "npm:core-js@1.1.4/library/modules/$.cof.js",
      "npm:core-js@1.1.4/library/modules/$.defined.js",
      "npm:core-js@1.1.4/library/modules/$.is-object.js",
      "npm:core-js@1.1.4/library/modules/$.strict-new.js",
      "npm:core-js@1.1.4/library/modules/$.library.js",
      "npm:core-js@1.1.4/library/modules/$.a-function.js",
      "npm:core-js@1.1.4/library/modules/$.same.js",
      "npm:core-js@1.1.4/library/modules/$.uid.js",
      "npm:core-js@1.1.4/library/modules/$.collection-to-json.js",
      "npm:core-js@1.1.4/library/modules/$.an-object.js",
      "npm:core-js@1.1.4/library/modules/$.ctx.js",
      "npm:core-js@1.1.4/library/modules/$.classof.js",
      "npm:core-js@1.1.4/library/modules/$.for-of.js",
      "npm:core-js@1.1.4/library/modules/$.wks.js",
      "npm:core-js@1.1.4/library/modules/$.species.js",
      "npm:core-js@1.1.4/library/modules/$.support-desc.js",
      "npm:core-js@1.1.4/library/modules/$.mix.js",
      "npm:core-js@1.1.4/library/modules/$.microtask.js",
      "npm:core-js@1.1.4/library/modules/$.tag.js",
      "npm:core-js@1.1.4/library/modules/$.iter-detect.js",
      "github:jspm/nodelibs-process@0.1.1.js",
      "npm:process@0.11.2/browser.js",
      "npm:core-js@1.1.4/library/modules/$.has.js",
      "npm:core-js@1.1.4/library/modules/$.to-integer.js",
      "npm:core-js@1.1.4/library/modules/$.iter-step.js",
      "npm:core-js@1.1.4/library/modules/$.unscope.js",
      "npm:core-js@1.1.4/library/modules/$.hide.js",
      "npm:core-js@1.1.4/library/modules/$.iter-create.js",
      "npm:core-js@1.1.4/library/modules/$.redef.js",
      "npm:core-js@1.1.4/library/modules/$.iter-call.js",
      "npm:core-js@1.1.4/library/modules/$.is-array-iter.js",
      "npm:core-js@1.1.4/library/modules/core.get-iterator-method.js",
      "npm:core-js@1.1.4/library/modules/$.to-length.js",
      "npm:core-js@1.1.4/library/modules/$.shared.js",
      "npm:core-js@1.1.4/library/modules/$.task.js",
      "github:jspm/nodelibs-process@0.1.1/index.js",
      "npm:core-js@1.1.4/library/modules/$.invoke.js",
      "npm:core-js@1.1.4/library/modules/$.property-desc.js",
      "npm:core-js@1.1.4/library/modules/$.html.js",
      "npm:core-js@1.1.4/library/modules/$.dom-create.js",
      "npm:process@0.10.1.js",
      "npm:process@0.10.1/browser.js"
    ]
  },
  globalEvaluationScope: false,

  map: {
    "babel": "npm:babel-core@5.8.25",
    "babel-runtime": "npm:babel-runtime@5.8.24",
    "core-js": "npm:core-js@1.1.4",
    "css": "github:systemjs/plugin-css@0.1.17",
    "hammer": "github:hammerjs/hammer.js@2.0.6",
    "handlebars": "github:components/handlebars.js@4.0.5",
    "json": "github:systemjs/plugin-json@0.1.0",
    "loglevel": "npm:loglevel@1.4.0",
    "q": "npm:q@1.4.1",
    "text": "github:systemjs/plugin-text@0.0.2",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.24": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@1.1.4": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:loglevel@1.4.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:q@1.4.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
