YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "Map",
        "MapDataManipulator",
        "ObjectManager",
        "Preload",
        "UI",
        "UITemplateBase",
        "UIs.default",
        "eventListeners",
        "extensions.baseEventlisteners",
        "extensions.hexagons.ObjectHexaTerrain",
        "extensions.hexagons.ObjectHexaUnit",
        "extensions.hexagons.selectHexagonObject",
        "extensions.hexagons.setupHexagonClick",
        "extensions.hexagons.utils",
        "extensions.hexagons.utils.getHexagonPoints.utils",
        "extensions.mapDrag",
        "extensions.mapMovement",
        "extensions.mapZoom",
        "generalUtils.polyfills",
        "log",
        "mapApi",
        "mapEvents",
        "mapStates",
        "maplayers.MapLayer",
        "maplayers.MapLayerParent",
        "maplayers.MapSubcontainer",
        "objects.ObjectSprite",
        "objects.ObjectSpriteTerrain",
        "objects.ObjectSpriteUnit",
        "utilities.arrays",
        "utilities.environmentDetections",
        "utils.Quadtree",
        "utils.dataManipulation",
        "utils.effects",
        "utils.environment",
        "utils.general",
        "utils.mouse",
        "utils.resize"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});