YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "Map",
        "MapDataManipulator",
        "MapLayer",
        "MapLayerParent",
        "MapSubcontainer",
        "ObjectManager",
        "ObjectSprite",
        "ObjectSpriteTerrain",
        "ObjectSpriteUnit",
        "Preload",
        "UI",
        "UIDefault",
        "UITemplateBase",
        "baseEventlisteners",
        "eventListeners",
        "generalUtils.polyfills",
        "hexagonPlugin.ObjectHexaTerrain",
        "hexagonPlugin.ObjectHexaUnit",
        "hexagonPlugin.setupHexagonClick",
        "hexagonPlugin.setupObject_select_hexagon",
        "hexagonPlugin.utils",
        "log",
        "mapApi",
        "mapDrag",
        "mapEvents",
        "mapMovement",
        "mapStates",
        "mapZoom",
        "utilities.arrays",
        "utilities.environmentDetections",
        "utils.Quadtree",
        "utils.dataManipulation",
        "utils.effects",
        "utils.environment",
        "utils.general",
        "utils.mouse",
        "utils.resize"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});